spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${PL_KAKAO_API_KEY}
            redirect-uri: ${PL_KAKAO_REDIRECT_URL}
            client-secret: ${PL_KAKAO_SECRET_KEY}
            authorization-grant-type: authorization_code
            scope: profile,account_email
            provider: kakao
          naver:
            client-id: ${PL_NAVER_API_KEY}
            redirect-uri: ${PL_NAVER_REDIRECT_URL}
            client-secret: ${PL_NAVER_SECRET_KEY}
            authorization-grant-type: authorization_code
            scope: profile,account_email
            provider: naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

